#!/bin/sh

### This script will be executed when package installed and upgraded.
### Actions after package installed.
### ex. create database, create symbolic link...
pkg_path="/var/packages"
hdhr_pkg_path="/var/packages/HDHomeRunDVR"
hdhr_web_path="$hdhr_pkg_path/target/web"
hdhr_bin_path="$hdhr_pkg_path/target/bin"
hdhr_etc_path="$hdhr_pkg_path/target/etc"
syn_web_path="/var/services/web/HDHomeRunDVR"
hdhr_bin="hdhomerun_record_linux"
hdhr_conf="HDHomeRunDVR.conf"


create_web_ui() {
	cp -R $hdhr_web_path $syn_web_path
	chown -R http:http $syn_web_path
}

delete_web_ui() {
	rm -rf $syn_web_path
}

create_recordings_path() {
	echo "Does Nothing"
}

remove_recordings_path() {
	echo "Does Nothing"
}

save_tmp_conf() {
	echo "Does Nothing"
}

restore_tmp_conf() {
	echo "Does Nothing"
}

start_engine() {
	$hdhr_bin_path/$hdhr_bin start --conf $hdhr_etc_path/$hdhr_conf
}

stop_engine() {
	$hdhr_bin_path/$hdhr_bin stop
}

status_engine() {
	$hdhr_bin_path/$hdhr_bin version
	$hdhr_bin_path/$hdhr_bin status
}

