#!/bin/sh

#package_path=$(dirname "$0")
#. $package_path/common

case "$1" in
  start)
    #start_engine
    ;;

  stop)
    #stop_engine
    ;;

  restart)
    #start_engine
    #stop_engine
    ;;

  status)
    #status_engine
    ;;

  *)
    echo "Usage: $0 {start|stop|status|restart}"
    exit 1
esac

exit 0
